### ISSUE TITLE
some issues with native.crs

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/mapview#93] opened 2017-07-24 11:47 UTC
I'm getting mixed results from projected inputs in native view. 

These "bgm" packages support a "box geometry" model used in ecosystem modelling.  Each one has a native local map projection, in this case it's a Lambert Azimuthal Equal Area. 

Load up sp polygons from a model. 

```R
library(bgmfiles)
library(rbgm)
library(mapview)
bfile <- bgmfiles("antarctica_28")
model <- bgmfile(bfile)
bgmbox <- boxSpatial(model)
```

Now mapview, it works fine in native.crs when used as, but not when left as polygons. 

```R
mapview(faceSpatial(model), native.crs = TRUE)
mapview(bgmbox, native.crs = TRUE)
## it does work if we fudge-fix the topology
mapview(rgeos::gBuffer(bgmbox, byid = TRUE, width = 0), native.crs = TRUE)
```

Many of the files have some unresolved issues, and presumably my conversion to Spatial has some issues too, but I'm not sure I'd  connected this missing features to a "solution" before.

**Comment by tim-salabim** [comment] 2017-07-25 17:46
I think I've narrowed it down to the names of the sf geometry list column (which are dropped when buffering). Note, that I am debugging the sf, as the first thing mapview does is `st_as_sf`. 

```r
bgmbox_sf = st_as_sf(bgmbox)
sapply(st_geometry(bgmbox_sf), names)

 [1] "Box0"  "Box1"  "Box2"  "Box3"  "Box4"  "Box5"  "Box6"  "Box7"  "Box8"  "Box9"  "Box10"
[12] "Box11" "Box12" "Box13" "Box14" "Box15" "Box16" "Box17" "Box18" "Box19" "Box20" "Box21"
[23] "Box22" "Box23" "Box24" "Box25" "Box26" "Box27"

names(st_geometry(bgmbox_sf)[[1]]) = NULL
names(st_geometry(bgmbox_sf)[[1]])

NULL

names(st_geometry(bgmbox_sf)[[2]])

[1] "Box1"

mapview(bgmbox_sf, native.crs = TRUE) # only plots "Box0" as it doesn't have name anymore
```
I've checked, and the same holds true for the sp version. Names of the `@Polygons` slots get dropped by `gBuffer`. 

I am still trying to come up with a safe way to handle such things - so this is not resolved. 
I need to come up with some serious checking to avoid such issues. Any hints on how to make sure that geometry list columns are unnamed would be welcome (also pinging @edzer on this one).

On a broader scale I think the problem is that JS doesn't like named objects but @timelyportfolio or @bhaskarvk can maybe shed more light on this. Anyway, JS isn't really helpful by simply not doing anything. Even the console output isn't very helpful (at least to me).

**Comment by edzer** [comment] 2017-07-25 18:50
```r
sapply(bgmbox@polygons, slot, name = "ID")
 [1] "Box0"  "Box1"  "Box2"  "Box3"  "Box4"  "Box5"  "Box6"  "Box7"  "Box8" 
[10] "Box9"  "Box10" "Box11" "Box12" "Box13" "Box14" "Box15" "Box16" "Box17"
[19] "Box18" "Box19" "Box20" "Box21" "Box22" "Box23" "Box24" "Box25" "Box26"
[28] "Box27"
```
but
```r
> names(st_geometry(bgmbox_sf))
NULL
```
I think in the conversion from sp -> sf, the naming of `st_geometry(bgmbox_sf)[[i]]` was not a good idea. However it happened because
```r
> names(bgmbox@polygons[[1]]@Polygons)
[1] "Box0"
```
after which it got simply copied. I've never seen this slot being named, e.g.
```r
> nc <- readOGR(system.file("shapes/", package="maptools"), "sids")
OGR data source with driver: ESRI Shapefile 
Source: "/home/edzer/R/x86_64-pc-linux-gnu-library/3.4/maptools/shapes/", layer: "sids"
with 100 features
It has 14 fields
Integer64 fields read as strings:  CNTY_ CNTY_ID FIPSNO 
> names(nc@polygons[[1]]@Polygons)
NULL
```
and since `Polygons` is a list for all the rings, naming it with the `ID` doesn't make sense. I suggest to change the `boxSpatial` function that created this object with named `Polygons` slots such that it doesn't name them.

**Comment by mdsumner** [comment] 2017-07-25 20:51
Aha thanks!

**Comment by tim-salabim** [comment] 2017-08-01 11:57
Closing this. Re-open if you think this needs further addressing on mapview side

**Closed by tim-salabim** 2017-08-01 11:57 UTC
