### ISSUE TITLE
problem with `burst` when combining two maps with `+`

### ISSUE THREAD

**Issue by floswald** [r-spatial/mapview#357] opened 2020-12-17 10:06 UTC
I have two sf dataframes, and I want to map them together in separate layers _and_ using burst for each of them. 
both datasets are [here](https://www.dropbox.com/sh/2hyjmjj1y895hmw/AABnh3MQRlYtvNzn8UzcPy4Ya?dl=0) (168Kb) 

dataset 1:

```
> garages
Simple feature collection with 95 features and 4 fields
Attribute-geometry relationship: 4 constant, 0 aggregate, 0 identity
geometry type:  POINT
dimension:      XY
bbox:           xmin: 504969.3 ymin: 161821.9 xmax: 559132.1 ymax: 209588.7
projected CRS:  OSGB 1936 / British National Grid
First 10 features:
   garagecode                  garage  op_group        garage_name                  geometry
1           A              Sutton (A)   Goahead             Sutton   POINT (525477.2 164896)
2          AC          Willesden (AC) Metroline          Willesden POINT (522260.5 184740.2)
3          AD      Palmers Green (AD)    Arriva      Palmers Green POINT (531062.3 192142.7)
4          AE          Ash Grove (AE)    Arriva          Ash Grove POINT (534962.3 184347.1)
5          AF             Putney (AF)   Goahead             Putney POINT (523940.7 175227.4)
6          AH          Brentford (AH) Metroline          Brentford POINT (517265.3 177322.1)
7          AL             Merton (AL)   Goahead             Merton POINT (523910.6 171104.6)
8          AR           Edmonton (EC)    Arriva          Tottenham   POINT (533605.9 189510)
9          AV           Hounslow (AV)      RATP           Hounslow POINT (514288.8 176072.4)
10         AW Walthamstow Avenue (AW)       HCT Walthamstow Avenue POINT (537335.2 191103.4)
```

dataset 2:

```
> routes
Simple feature collection with 664 features and 4 fields
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: 497660 ymin: 148922 xmax: 561242 ymax: 201499
projected CRS:  OSGB 1936 / British National Grid
# A tibble: 664 x 5
   route     n operator      op_group                                                               geometry
   <chr> <int> <chr>         <chr>                                                          <LINESTRING [m]>
 1 1        29 London Centr… Goahead  (529998 181428, 530237 181523, 530560 181433, 530822 181068, 530747 1…
 2 100      24 London Centr… Goahead  (532026 181450, 532062 181569, 532262 181570, 532638 181583, 532987 1…
 3 101      44 Blue Triangle Goahead  (540542 188400, 540584 188379, 540531 188177, 540338 187890, 540338 1…
 4 102      60 Arriva London Arriva   (534466 193632, 534300 193316, 534273 193148, 534189 192782, 534144 1…
 5 103      44 Arriva London Arriva   (551008 191700, 551092 191540, 551026 191381, 550856 191140, 550773 1…
 6 104      36 Blue Triangle Goahead  (538669 184304, 538989 184292, 539222 183982, 539300 183949, 539601 1…
 7 105      44 London United RATP     (514833 183965, 514788 183864, 514679 183691, 514616 183400, 514735 1…
 8 106      35 London Gener… Goahead  (531407 186807, 531569 186720, 531870 186484, 532018 186565, 532369 1…
 9 107      50 Metroline     Metroli… (519591 191841, 519480 192045, 519354 192413, 519333 192738, 519056 1…
10 108      39 London Centr… Goahead  (538136 184846, 538275 184847, 538522 184583, 538194 184174, 538435 1…
```

I can map them together:

```
mapview(list(routes,garages),zcol = list("op_group","op_group"))
# or 
# mapview(routes,zcol = "op_group") +mapview(garages,zcol = "op_group")
```

and I can give a burst to one of them:

```
mapview(routes,zcol = "op_group") +mapview(garages,zcol = "op_group",burst = TRUE)
# or
# mapview(routes,zcol = "op_group",burst = TRUE) +mapview(garages,zcol = "op_group")
```
<img width="922" alt="Screenshot 2020-12-17 at 10 57 57" src="https://user-images.githubusercontent.com/1021558/102473024-3de9d880-4057-11eb-915b-ea4567847bd9.png">

but I want to have the burst on both, which does not work:

```
mapview(routes,zcol = "op_group",burst = TRUE) +mapview(garages,zcol = "op_group",burst = TRUE)
```
<img width="919" alt="Screenshot 2020-12-17 at 10 57 33" src="https://user-images.githubusercontent.com/1021558/102473048-46421380-4057-11eb-99a9-aa58c3cbf64b.png">

It seems it creates an enclosing polygon rather mapping both lines and points separately. notice that this is not due to column names:

```
> routes = rename(routes, op2 = op_group)
mapview(routes,zcol = "op2",burst = TRUE) +mapview(garages,zcol = "op_group",burst = TRUE)
```

creates the same picture as above. thanks for any hints!

**Comment by tim-salabim** [comment] 2020-12-22 16:29
Hi @floswald this is a bit tricky as both burst columns have the same labels (which I assume is on purpose). If `burst  = TRUE` and a `zcol` is set, it means that layer group names are taken from the labels/values of `zcol`. But then any two layers from each data set have the same layer names and leaflet is not able to distinguish which one to draw, or better doesn't re-draw an already existing layer (but it seems that it updates the options of the layer - hence the fill of the lines). If you reverse your call, you will only see the points, not the lines:

```r
mapview(garages, zcol = "op_group", burst = TRUE) +
  mapview(routes, zcol = "op_group", burst = TRUE)
```
![image](https://user-images.githubusercontent.com/2826432/102909066-adf1c780-4478-11eb-9efd-d9b879d0c8b1.png)

Given that you want to mix points and lines I fear there's no other solution than to rename the burst/zcol column labels/values, e.g.

```r
routes$op_group = paste0(routes$op_group, ".rd")

mapview(routes, zcol = "op_group", burst = TRUE) +
  mapview(garages, zcol = "op_group", burst = TRUE)
```
![image](https://user-images.githubusercontent.com/2826432/102909750-bbf41800-4479-11eb-9222-a026101d1262.png)

There's also the possibility to `st_union` the specific points and lines representing each zcol label and then `mapview` that list, but then we still have the problem that we can only set `fill = TRUE` once per layer and the lines will either be filled or the points won't be... Here's an example showing what I mean.

```r
trls = st_transform(trails, 4326)
tst = st_union(breweries[1, ], trls[2, ])

mapview(tst)
```
![image](https://user-images.githubusercontent.com/2826432/102910137-5a807900-447a-11eb-90b7-b7c40e1252fb.png)

I am afraid, there's no sensible way to make this work in mapview. Maybe this is possible in **tmap** (@mtennekes ?) or you'd need to put this together yourself in **leaflet** (which I think would involve careful creation of layerIds for each layer group).

**Comment by floswald** [comment] 2020-12-22 18:00
Thanks for the explanation! I thought the column names was the solution but you see I changed it at the end of my post. I don't understand why that doesn't work while what you did does - anyway I'll copy your code as I just need something that works for now. Thanks again!

**Comment by tim-salabim** [comment] 2020-12-22 18:10
The problem is that the values of the two columns from the two objects are identical (or at least overlapping). If you `burst` these need to be distinct for each map, as you cannot add a layer with the same name twice (or more precisely, the implementation of mapview does not allow for adding features to an already existing layer). 

I guess what we could do, is to paste together the column name and the value for the layer names. Then your attempt at changing the column names would work. I am a bit reluctant though, as it would clutter the legend quite a lot...

**Comment by floswald** [comment] 2020-12-22 18:48
Ah ok! I got it . Makes sense. No worries how you did it with the paste is
a perfectly workable solution for me right now. Thanks !

**Comment by tim-salabim** [comment] 2020-12-22 18:58
Sweet. I'll close this here. Feel free to re-open if needed

**Closed by tim-salabim** 2020-12-22 18:58 UTC
