### ISSUE TITLE
Mapview and st_intersection gives odd results

### ISSUE THREAD

**Issue by nekronaut** [r-spatial/mapview#371] opened 2021-04-08 14:53 UTC
Doing a simple clip via st_intersection gives odd results, where grouping variables are no longer mapped, i.e. all objects appear in the same colour, independent of what the legend shows. Let me demonstrate:

    library(mapview)
    library(sf)
    library(rnaturalearth)

    rivers <- ne_download(scale = 10, type = 'rivers_lake_centerlines', category = "physical", returnclass = "sf")
    de <- ne_countries(country = "germany", returnclass = "sf")
    rivers_de_st <- rivers %>% st_intersection(de)
    mapview(rivers_de_st, zcol = "name")

It's not a problem with the data, as `plot` gives the expected result:

    plot(rivers_de_st["name"])

I can do a workaround, by subsetting with `[]` but that does not clip the lines to the polygon.

    rivers_de_sub <- rivers[de,]
    mapview(rivers_de_sub, zcol = "name")

I'm sure this has a very simple solution - any suggestions?

**Comment by tim-salabim** [comment] 2021-04-08 15:17
I cannot reproduce the issue:

``` r
library(mapview)
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
library(rnaturalearth)

rivers <- ne_download(scale = 10, type = 'rivers_lake_centerlines', category = "physical", returnclass = "sf")
#> OGR data source with driver: ESRI Shapefile 
#> Source: "/tmp/RtmpG99QZi", layer: "ne_10m_rivers_lake_centerlines"
#> with 1455 features
#> It has 34 fields
#> Integer64 fields read as strings:  rivernum ne_id
#> Warning in rgdal::readOGR(destdir, file_name, encoding = "UTF-8",
#> stringsAsFactors = FALSE, : Dropping null geometries: 1453
de <- ne_countries(country = "germany", returnclass = "sf")
rivers_de_st <- rivers %>% st_intersection(de)
#> although coordinates are longitude/latitude, st_intersection assumes that they are planar
#> Warning: attribute variables are assumed to be spatially constant throughout all
#> geometries
mapview(rivers_de_st, zcol = "name")
```

![](https://i.imgur.com/HbrVhIT.png)

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Can you tr``` r
library(mapview)
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
library(rnaturalearth)

rivers <- ne_download(scale = 10, type = 'rivers_lake_centerlines', category = "physical", returnclass = "sf")
#> OGR data source with driver: ESRI Shapefile 
#> Source: "/tmp/RtmpG99QZi", layer: "ne_10m_rivers_lake_centerlines"
#> with 1455 features
#> It has 34 fields
#> Integer64 fields read as strings:  rivernum ne_id
#> Warning in rgdal::readOGR(destdir, file_name, encoding = "UTF-8",
#> stringsAsFactors = FALSE, : Dropping null geometries: 1453
de <- ne_countries(country = "germany", returnclass = "sf")
rivers_de_st <- rivers %>% st_intersection(de)
#> although coordinates are longitude/latitude, st_intersection assumes that they are planar
#> Warning: attribute variables are assumed to be spatially constant throughout all
#> geometries
mapview(rivers_de_st, zcol = "name")
```

![](https://i.imgur.com/HbrVhIT.png)

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

What's your `sessionInfo()`?

**Comment by nekronaut** [comment] 2021-04-08 15:30
![Unbenannt](https://user-images.githubusercontent.com/60748916/114053682-74aa5f80-988f-11eb-8962-69839e780ea4.PNG)

This is my `sessioninfo`. I'm likely running outdated R and RStudio versions, as my employer only updates our software very infrequently...

    > sessionInfo()
    R version 3.6.2 (2019-12-12)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 17763)

    Matrix products: default

    locale:
    [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252      LC_NUMERIC=C                   
    [5] LC_TIME=German_Germany.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] rnaturalearth_0.1.0 sf_0.9-7            mapview_2.9.0      

    loaded via a namespace (and not attached):
    [1] tidyselect_1.1.0        purrr_0.3.4             lattice_0.20-38         leaflet.providers_1.9.0 colorspace_1.4-1       
    [6] vctrs_0.3.4             generics_0.1.0          htmltools_0.4.0         stats4_3.6.2            yaml_2.2.1             
    [11] base64enc_0.1-3         rlang_0.4.8             leafpop_0.0.5           e1071_1.7-3             later_1.0.0            
    [16] pillar_1.4.3            glue_1.4.2              DBI_1.1.0               gdtools_0.2.1           sp_1.4-4               
    [21] uuid_0.1-2              lifecycle_0.2.0         munsell_0.5.0           raster_3.4-5            htmlwidgets_1.5.1      
    [26] codetools_0.2-16        fastmap_1.0.1           httpuv_1.5.2            crosstalk_1.0.0         class_7.3-15           
    [31] leafem_0.1.3            Rcpp_1.0.3              KernSmooth_2.23-16      xtable_1.8-4            promises_1.1.0         
    [36] scales_1.1.0            classInt_0.4-3          satellite_1.0.2         jsonlite_1.6.1          leaflet_2.0.3          
    [41] webshot_0.5.2           farver_2.0.3            systemfonts_0.1.1       mime_0.8                brew_1.0-6             
    [46] png_0.1-7               digest_0.6.23           dplyr_1.0.2             shiny_1.4.0             grid_3.6.2             
    [51] rgdal_1.4-8             tools_3.6.2             magrittr_2.0.1          tibble_3.0.4            crayon_1.3.4           
    [56] pkgconfig_2.0.3         ellipsis_0.3.0          svglite_1.2.2           rstudioapi_0.13         R6_2.4.1               
    [61] units_0.6-5             compiler_3.6.2

**Comment by tim-salabim** [comment] 2021-04-08 16:06
Can you `remotes::install_github("r-spatial/mapview")`?

**Comment by nekronaut** [comment] 2021-04-09 07:06
Unfortunately, I get a timeout:

``` r
remotes::install_github("r-spatial/mapview")
#> Error: Failed to install 'mapview' from GitHub:
#>   Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Again, I think that is due to some sort of block, where my employer does not allow certain downloads. I have tried setting the ports and proxies, but it doesn't make any difference:

``` r
library(curl)
library(httr)
#> 
#> Attaching package: 'httr'
#> The following object is masked from 'package:curl':
#> 
#>     handle_reset

proxyPort <- ie_get_proxy_for_url()
proxyURL  <- strsplit(proxyPort, ":")[[1]][1]
portUsed  <- as.integer(strsplit(proxyPort, ":")[[1]][2])
set_config(use_proxy(url=proxyURL, port = portUsed), override = TRUE)
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tim-salabim** [comment] 2021-04-11 08:38
I think you should first try to convince your employer to update your software, before we dig any deeper into this. This may have been a bug that is already fixed...

**Comment by nekronaut** [comment] 2021-04-12 14:01
I have updated to R 4.0.5 and RStudio 1.4.1106. Unfortunately, running the above `mapview` code example now displays no line-objects at all:

![image](https://user-images.githubusercontent.com/60748916/114402370-0a9dfd00-9ba4-11eb-90bf-0aaeae506a3a.png)

Using `leaflet`, however, gives the expected results (not sure why `reprex` thinks that certain functions can't be found...):

``` r
cols <- colorFactor(palette = "viridis", domain = rivers_de_st$name)
#> Error in colorFactor(palette = "viridis", domain = rivers_de_st$name): could not find function "colorFactor"

leaflet() %>% 
  addTiles() %>% 
  addPolylines(data = rivers_de_st,
               color = ~cols(name)) %>% 
  addLegend(pal = cols,
            values = rivers_de_st$name)
#> Error in leaflet() %>% addTiles() %>% addPolylines(data = rivers_de_st, : could not find function "%>%"
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

![image](https://user-images.githubusercontent.com/60748916/114406073-877ea600-9ba7-11eb-8241-a32f18a3f292.png)

**Comment by tim-salabim** [comment] 2021-04-12 14:50
Can you give me your `sessionInfo()` & also the output of `sf::sf_extSoftVersion()` ?

**Comment by nekronaut** [comment] 2021-04-12 14:54
``` r
sessionInfo()
#> R version 4.0.5 (2021-03-31)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17763)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
#> [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.31        magrittr_2.0.1    rlang_0.4.10      fansi_0.4.2      
#>  [5] stringr_1.4.0     styler_1.4.1      highr_0.8         tools_4.0.5      
#>  [9] xfun_0.22         utf8_1.2.1        withr_2.4.1       htmltools_0.5.1.1
#> [13] ellipsis_0.3.1    yaml_2.2.1        digest_0.6.27     tibble_3.1.0     
#> [17] lifecycle_1.0.0   crayon_1.4.1      purrr_0.3.4       vctrs_0.3.7      
#> [21] fs_1.5.0          glue_1.4.2        evaluate_0.14     rmarkdown_2.7    
#> [25] reprex_2.0.0      stringi_1.5.3     compiler_4.0.5    pillar_1.5.1     
#> [29] backports_1.2.1   pkgconfig_2.0.3
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

``` r
sf::sf_extSoftVersion()
#>           GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
#>        "3.9.0"        "3.2.1"        "7.2.1"         "true"         "true"
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tim-salabim** [comment] 2021-04-12 14:59
And `packageVersion("mapview")`? Sorry, I thought you had loaded it when running sessionInfo

**Comment by nekronaut** [comment] 2021-04-12 15:04
Sorry, my fault - was doing something else and had started a new session.

``` r
packageVersion("mapview")
#> [1] '2.9.0'
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tim-salabim** [comment] 2021-04-12 15:35
Yeah, there are some bugs in 2.9.0

Honestly, the best would be to update mapview, leafem & leafpop from github. I still haven't had a chance to update them on CRAN but hope to get them updated in the near future.

You can also try to set `mapviewOptions(fgb = FALSE)` before you create the map, but I doubt that it will actually solve the issue (but we might be lucky).

**Comment by nekronaut** [comment] 2021-04-12 16:49
I finally remembered, that I can install packages from locally saved zip files. So with the up to date versions of mapview, leafem and leafpop the problem no longer occurs. Thanks for you patience and advice!

However, now neither `viewer.suppress = TRUE`, nor `options(viewer = NULL)` work any longer. This is a fairly large issue for me, as - probably for the same reasons that I can't directly download packages from github - background maps are not shown within the RStudio viewer window and I have been using this workaround to display maps in the browser. Have these functions been deprecated?

**Comment by tim-salabim** [comment] 2021-04-12 17:25
No they should definitely still work. I've worked on the print method for mapview recently, so maybe I've introduced a bug there... I'll check and get back to you

**Comment by nekronaut** [comment] 2021-04-13 08:42
Have just found that enlarging the viewer window displays background maps. Sorry, have gotten so used to blocking the map in the viewer that I didn't immediately think of that solution. Still may be worth while checking whether there is a bug, concerning `viewer.suppress = TRUE` and `options(viewer = NULL)`. Thanks again for your help and thanks for a great package!

**Comment by tim-salabim** [comment] 2021-04-18 12:47
Ok, I remember now. I've chosen to implement all this via a mapview specific option. 

```r
library(mapview)

mapviewOptions(viewer.suppress = TRUE)

mapview(franconia)
```
should render in browser instead of RStudio viewer. This also means that `viewer.suppress = TRUE` inside a mapview call doesn't work anymore... I should probably document this.

**Comment by nekronaut** [comment] 2021-04-20 14:54
Great, thanks for clearing this up!

On 18 April 2021 14:47:27 CEST, tim-salabim ***@***.***> wrote:
>Ok, I remember now. I've chosen to implement all this via a mapview
>specific option. 
>
>```r
>library(mapview)
>
>mapviewOptions(viewer.suppress = TRUE)
>
>mapview(franconia)
>```
>should render in browser instead of RStudio viewer. This also means
>that `viewer.suppress = TRUE` inside a mapview call doesn't work
>anymore... I should probably document this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/r-spatial/mapview/issues/371#issuecomment-821986577

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tim-salabim** [comment] 2021-04-20 15:27
Can we close this?

**Comment by nekronaut** [comment] 2021-04-21 05:02
Yes.

On 20 April 2021 17:27:53 CEST, tim-salabim ***@***.***> wrote:
>Can we close this?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/r-spatial/mapview/issues/371#issuecomment-823367015

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2021-04-21 05:56 UTC
