### ISSUE TITLE
save map with fractional zoom using mapshot

### ISSUE THREAD

**Issue by tdwils** [r-spatial/mapview#274] opened 2020-04-02 15:14 UTC
It seems that mapshot is rounding the zoom level to the nearest integer when the map to be exported has a fractional zoom.

For example, the mapshot command below creates identical png files for both zoom = 4.6 and zoom = 5.0. Is there a way to save the map with a fractional zoom level?

```r
library(leaflet)
library(mapview)

# Create map with fractional zoom
mymap <- leaflet(options = leafletOptions(zoomSnap = 0, zoomDelta = 0.1)) %>% 
  addTiles() %>% 
  setView(lng = -100, lat = 37.8, zoom = 4.6) 

# View map
mymap

# Save map as png
mapshot(mymap, file = "mymap.png")
```

Many thanks!

**Comment by kaimath** [comment] 2020-05-26 19:38
Hi @tdwils ,

I was frustrated with the same problem, but I found a working solution. I'm not sure how the specifics work, but I can tell you how to implement it. Hopefully this will help future users who encounter the same problem!

I spent a lot of time trying to diagnose the problem, and the problem is not with fractional zoom (as you have enabled it in your sample map code). You will be able to tell this if you save your map as an HTML file -- fractional zoom is very much enabled.

The problem is actually with mapshot--more specifically, mapshot relies on webshot, which relies on PhantomJS. I found this thread to be very helpful: https://github.com/Leaflet/Leaflet/issues/6111

I simply copied the user agent this person defined, and pasted it in as an option into mapshot. This solved my problem with fractional zoom.

`mymap %>% mapshot(mymap, file = "mymap.png", 
useragent = 'Mozilla/5.0 (compatible; MSIE 10.6; Windows NT 6.1; Trident/5.0; InfoPath.2; SLCC1; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 2.0.50727) 3gpp-gba UNTRUSTED/1.0')`

Honestly, I have very little understanding of what a user agent is, but my basic understanding is that the default headless browser is not the right type, and that using this user agent instead allows the fractional zoom to render properly, while the default user agent converts fractional zoom values to integers.

Please let me know if for any reason this does not work for you!

~Kai

**Comment by tdwils** [comment] 2020-05-28 22:06
Thank you very much for this idea. This seems like a good solution for now.

**Comment by tim-salabim** [comment] 2020-06-27 11:09
Closing here, as this is not directly related to mapview and seems to be acceptably resolved.

**Closed by tim-salabim** 2020-06-27 11:09 UTC
