### ISSUE TITLE
mapview with FlatGeoBuf not rendering

### ISSUE THREAD

**Issue by dickoa** [r-spatial/mapview#313] opened 2020-08-15 10:59 UTC
Hi @tim-salabim,

Thanks for this great release and your work on this awesome package.
I have an issue the fgb option set to `TRUE`

```r
library(mapview)
# GDAL version >= 3.1.0 | setting mapviewOptions(fgb = TRUE)
mapview(breweries)
```

![fgb_true](https://user-images.githubusercontent.com/500140/90310940-b132e080-dee5-11ea-80f6-cfb2e75e93eb.png)

When I set it to `FALSE` it works

```r
mapviewOptions(fgb = FALSE)
mapview(breweries)
```

![fgb_false](https://user-images.githubusercontent.com/500140/90310942-b55efe00-dee5-11ea-89f5-bff2ad29193d.png)

I don't have any errors or warnings so I don't know how I can debug this

Geospatial library I used

```r
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.8.0"        "3.1.2"        "7.1.0"         "true" 
    USE_PROJ_H 
        "true" 
```

<details>
<summary>R session</summary>

```r

─ Session info ────────────────────────────────────────────────
 setting  value                                      
 version  R version 4.0.2 Patched (2020-07-31 r78945)
 os       Arch Linux                                 
 system   x86_64, linux-gnu                          
 ui       X11                                        
 language (EN)                                       
 collate  en_US.UTF-8                                
 ctype    en_US.UTF-8                                
 tz       UTC                                        
 date     2020-08-15                                 

─ Packages ────────────────────────────────────────────────────
 package           * version date       lib
 assertthat          0.2.1   2019-03-21 [1]
 backports           1.1.8   2020-06-17 [1]
 base64enc           0.1-3   2015-07-28 [1]
 brew                1.0-6   2011-04-13 [1]
 callr               3.4.3   2020-03-28 [1]
 class               7.3-17  2020-04-26 [1]
 classInt            0.4-3   2020-04-07 [1]
 cli                 2.0.2   2020-02-28 [1]
 codetools           0.2-16  2018-12-24 [1]
 colorspace          1.4-1   2019-03-18 [1]
 crayon              1.3.4   2017-09-16 [1]
 crosstalk           1.1.0.1 2020-03-13 [1]
 DBI                 1.1.0   2019-12-15 [1]
 desc                1.2.0   2018-05-01 [1]
 devtools            2.3.1   2020-07-21 [1]
 digest              0.6.25  2020-02-23 [1]
 dplyr               1.0.1   2020-07-31 [1]
 e1071               1.7-3   2019-11-26 [1]
 ellipsis            0.3.1   2020-05-15 [1]
 fansi               0.4.1   2020-01-08 [1]
 fs                  1.5.0   2020-07-31 [1]
 gdtools             0.2.2   2020-04-03 [1]
 generics            0.0.2   2018-11-29 [1]
 glue                1.4.1   2020-05-13 [1]
 htmltools           0.5.0   2020-06-16 [1]
 htmlwidgets         1.5.1   2019-10-08 [1]
 jsonlite            1.7.0   2020-06-25 [1]
 KernSmooth          2.23-17 2020-04-26 [1]
 lattice             0.20-41 2020-04-02 [1]
 leafem              0.1.3   2020-07-26 [1]
 leaflet             2.0.3   2019-11-16 [1]
 leaflet.providers   1.9.0   2019-11-09 [1]
 leafpop             0.0.5   2019-12-09 [1]
 lifecycle           0.2.0   2020-03-06 [1]
 magrittr            1.5     2014-11-22 [1]
 mapview           * 2.9.0   2020-08-15 [1]
 memoise             1.1.0   2017-04-21 [1]
 munsell             0.5.0   2018-06-12 [1]
 pillar              1.4.6   2020-07-10 [1]
 pkgbuild            1.1.0   2020-07-13 [1]
 pkgconfig           2.0.3   2019-09-22 [1]
 pkgload             1.1.0   2020-05-29 [1]
 png                 0.1-7   2013-12-03 [1]
 prettyunits         1.1.1   2020-01-24 [1]
 processx            3.4.3   2020-07-05 [1]
 ps                  1.3.4   2020-08-11 [1]
 purrr               0.3.4   2020-04-17 [1]
 R6                  2.4.1   2019-11-12 [1]
 raster              3.3-13  2020-07-17 [1]
 RColorBrewer        1.1-2   2014-12-07 [1]
 Rcpp                1.0.5   2020-07-06 [1]
 remotes             2.2.0   2020-07-21 [1]
 rlang               0.4.7   2020-07-09 [1]
 rprojroot           1.3-2   2018-01-03 [1]
 satellite           1.0.2   2019-12-09 [1]
 scales              1.1.1   2020-05-11 [1]
 sessioninfo         1.1.1   2018-11-05 [1]
 sf                  0.9-6   2020-08-14 [1]
 sp                  1.4-2   2020-05-20 [1]
 svglite             1.2.3.2 2020-07-07 [1]
 systemfonts         0.2.3   2020-06-09 [1]
 testthat            2.3.2   2020-03-02 [1]
 tibble              3.0.3   2020-07-10 [1]
 tidyselect          1.1.0   2020-05-11 [1]
 units               0.6-7   2020-06-13 [1]
 usethis             1.6.1   2020-04-29 [1]
 uuid                0.1-4   2020-02-26 [1]
 vctrs               0.3.2   2020-07-15 [1]
 webshot             0.5.2   2019-11-22 [1]
 withr               2.2.0   2020-04-20 [1]
 yaml                2.2.1   2020-02-01 [1]
 source                            
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 Github (r-spatial/mapview@371eceb)
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 Github (r-spatial/sf@f36719c)     
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)                    
 CRAN (R 4.0.2)  

```

</details>

**Comment by tim-salabim** [comment] 2020-08-15 11:01
Do you see any errors in the browser console? Open in browser, then press F12 and select console (in most browsers).

**Comment by dickoa** [comment] 2020-08-15 11:27
Thanks a lot @tim-salabim, here it's on Firefox v79.0

![error_fgb](https://user-images.githubusercontent.com/500140/90311296-ea208480-dee8-11ea-9619-f8a5ce2e4848.png)

And using the Brave browser v84.1.12.112, this is what I have

![brave_browser_error](https://user-images.githubusercontent.com/500140/90311330-67e49000-dee9-11ea-8826-33db50db7111.png)

When I use Rstudio it works in the Viewer and also when Rstudio launch the external browser (firefox for me). I think the only difference I can see, is the fact that  R cli on Linux try to open plain html file in the browser whereas with Rstudio there's server in the background (i.e the address starts with `localhost:12435` but with the cli is just `file:///`)

Thanks again,
Ahmadou

**Comment by tim-salabim** [comment] 2020-08-15 11:32
Yes, with `fgb = TRUE` we use the Javacript fetch API which does not allow `file:///`. There's not much we can do I think...

**Comment by dickoa** [comment] 2020-08-15 11:49
Thanks for the clarification. So for the moment `fgb = TRUE` works just with Rstudio automatically. 
I will try to see how to mimic what Rstudio does then. I use mostly Emacs ESS or the R client on the terminal and by default they launch the browser with `file:///`.

Thanks for looking into this

**Comment by tim-salabim** [comment] 2020-08-15 12:00
I just tested from the terminal and see the same behaviour as you do... So, yeah, figuring out how to serve html content via localhost from the file system would be the way to go

**Comment by tim-salabim** [comment] 2020-08-17 18:44
https://twitter.com/TimSalabim3/status/1295423336420388866?s=19

Some more discussion related to the topic in the above tweet

**Comment by pat-s** [comment] 2020-08-19 08:52
I am facing a similar/the same error when trying to vis a .shp file from https://shop.swisstopo.admin.ch/de/products/landscape/boundaries3D. (Sorry, no reprex because the download needs a checkbox being checked first)

```r
mapview::mapview(kanton)

Failed to create feature 0 in file27f370f13b28
Deleting layer not supported by driver `FlatGeobuf'
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Feature creation failed.
In addition: Warning messages:
1: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: ICreateFeature: Mismatched geometry type
2: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 6: DeleteLayer() not supported by this dataset.
```

It works with `mapviewOptions(fgb = FALSE)`.

```r
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.1"        "3.1.1"        "6.3.1"         "true"         "true" 
```

**Comment by tim-salabim** [comment] 2020-08-19 09:05
What does `sf::st_is_valid(kanton)` say?

**Comment by pat-s** [comment] 2020-08-19 09:13
```r
sf::st_is_valid(kanton)
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[19] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[37] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```

**Comment by edzer** [comment] 2020-08-19 09:17
What does `sapply(kanton, class)` give?

**Comment by pat-s** [comment] 2020-08-19 09:18
```r
sapply(kanton, class)

$OBJECTID
[1] "numeric"

$UUID
[1] "character"

$DATUM_AEND
[1] "Date"

$OBJEKTART
[1] "character"

$KANTONSNUM
[1] "character"

$KANTONSFLA
[1] "numeric"

$NAME
[1] "character"

$ICC
[1] "character"

$EINWOHNERZ
[1] "numeric"

$geometry
[1] "sfc_POLYGON" "sfc"   
```

**Comment by cole-brokamp** [comment] 2020-09-03 18:38
I experienced this same problem.  Should the `fgb` option be set to FALSE by default?  This really threw me for a loop when I couldn't get

```r
library(mapview)
mapview(breweries)
```

to work after a fresh install of R and `mapview` from CRAN.

**Comment by tim-salabim** [comment] 2020-09-03 19:14
@cole-brokamp is this in RStudio?

**Comment by cole-brokamp** [comment] 2020-09-04 12:52
no.  emacs / ess and just in terminal, both on macOS

**Comment by dickoa** [comment] 2020-09-04 13:05
Hi @cole-brokamp, 

It's not a proper fix but I use this to make it work for the moment.

```r
essviewer <- function(url, height, ...) {
  dir <- gsub("file://|/index.html", "", url)
  servr::httd(dir = dir)
}
options(viewer = essviewer)
```

I'm thinking about moving it to my .Rprofile (conditional on not being on Rstudio).

Ahmadou

**Comment by cole-brokamp** [comment] 2020-09-04 13:10
Thank you!

**Comment by tim-salabim** [comment] 2020-09-04 13:19
Thanks @dickoa and @cole-brokamp , I will soon have a look at how I can make this work generally. @dickoa have you had any issues with your workaround so far?

**Comment by dickoa** [comment] 2020-09-04 13:24
No issue so far on my side but I don't know the other packages that use the viewer from the options and how it can affect them to have this custom version. I will continue to test with other htmlwidgets and report back if there's any error.
One thing that need to be done is to test whether we are on Rstudio before changing the viewer, other than that there's no issue and I used it a lot the past week.

**Comment by tim-salabim** [comment] 2020-09-04 13:26
Thanks!

**Comment by tim-salabim** [comment] 2020-09-04 14:23
Ok, this seems to work from my terminal:

```r
library(mapview)

setMethod('print', signature(x = "mapview"),
          function (x, ..., view = interactive()) 
          {
            x = x@map
            viewer <- getOption("viewer")
            if (!is.null(viewer)) {
              viewerFunc <- function(url) {
                paneHeight <- x$sizingPolicy$viewer$paneHeight
                if (identical(paneHeight, "maximize")) 
                  paneHeight <- -1
                viewer(url, height = paneHeight)
              }
            }
            else {
              viewerFunc = function(url, height, ...) {
                dir <- gsub("file://|/index.html", "", url)
                suppressMessages(servr::httd(dir = dir))
              }
            }
            htmltools::html_print(
              htmltools::as.tags(x, standalone = TRUE)
              , viewer = if (view) viewerFunc
            )
            invisible(x)
          }
)

mapview(trails)
```
@dickoa @cole-brokamp @edzer (in case you have GDAL >= 3.1) can you please try this and let me know if it also works in your setup? This is basically modifying the standard `htmlwidgets:::print.htmlwidget` to not fallback to `utils::browseURL` if not in RStudio, but use @dickoa 's workaround. Given that we only define this for class `mapview`, it shouldn't interfere with any other htmlwidget based rendering...

**Comment by dickoa** [comment] 2020-09-04 14:47
It looks like a good solution and it works both in ESS/Terminal and Rstudio.
Thanks @tim-salabim

**Comment by tim-salabim** [comment] 2020-09-04 15:46
One minor hickup taht remains is to make sure that we can suppress the viewer even when in RStudio. With the current implementation this doesn't work, but shouldn't be too complicated I hope.

**Comment by tim-salabim** [comment] 2020-09-07 09:24
With fa4caa73a37637dd82008138a4b5bb0afa71b808 `mapviewOptions(viewer.suppress = TRUE)` should now work, even from within RStudio.

Closing here, please re-open if other things come up

**Closed by tim-salabim** 2020-09-07 09:24 UTC

**Comment by tim-salabim** [comment] 2020-09-07 09:27
@pat-s is your error still persisting? It looks like a different beast to me to be honest

**Comment by pat-s** [comment] 2020-09-07 16:43
I'm on vacay this week so can't test. But it's not that urgent, the workaround is OK.

You should be able to reproduce it by downloading the public data yourself if you're up to 🙂

**Comment by tim-salabim** [comment] 2020-09-07 19:11
Of course. Enjoy your holidays!

**Comment by cole-brokamp** [comment] 2020-09-08 13:02
had to make sure `servr` was installed, but yes -- it works fine for me. thanks!

**Comment by tim-salabim** [comment] 2020-09-08 13:42
Cool, thanks for the feedback

**Comment by markegge** [comment] 2021-07-02 21:30
For anyone running into this issue error within RStudio, check that you have stripped Z and M values from your geometries. In my case:

```R
> mapview(shp, zcol = "adt_18", legend = TRUE)
Failed to create feature 0 in file390e4171cbda
Deleting layer not supported by driver `FlatGeobuf'
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Feature creation failed.
In addition: Warning messages:
1: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: ICreateFeature: Mismatched geometry type
2: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 6: DeleteLayer() not supported by this dataset.
> mapview(st_zm(shp), zcol = "adt_18", legend = TRUE)
> # great success
```
