### ISSUE TITLE
mapshot() to png fails with "TypeError: Attempting to change the setter of an unconfigurable property"

### ISSUE THREAD

**Issue by SimonCoulombe** [r-spatial/mapview#249] opened 2019-11-27 02:34 UTC
Hi everyone,
I can't run the example from the manual.  It creates an empty map.png.  and returns 
> mapshot(m, file = paste0(getwd(), "/map.png"))
```
TypeError: Attempting to change the setter of an unconfigurable property.
TypeError: Attempting to change the setter of an unconfigurable property.
```
here is map.png:
![map](https://user-images.githubusercontent.com/23444900/69688692-c6848800-1094-11ea-9a8e-939fffb7c152.png)

Any idea?
Full code with version and sessionInfo() below
```
> library(mapview)
> m <- mapview(breweries)
> 
> 
> ## create standalone .html
> mapshot(m, url = paste0(getwd(), "/map.html"))
> 
> ## create standalone .png; temporary .html is removed automatically unless
> ## 'remove_url = FALSE' is specified
> mapshot(m, file = paste0(getwd(), "/map.png"))
TypeError: Attempting to change the setter of an unconfigurable property.
TypeError: Attempting to change the setter of an unconfigurable property.
> 
> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray               
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.7.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3              RColorBrewer_1.1-2      compiler_3.5.1          later_1.0.0             class_7.3-14            base64enc_0.1-3         tools_3.5.1             digest_0.6.23           packrat_0.5.0          
[10] jsonlite_1.6            viridisLite_0.3.0       satellite_1.0.1         evaluate_0.14           lifecycle_0.1.0         lattice_0.20-35         png_0.1-7               rlang_0.4.2             shiny_1.4.0            
[19] DBI_1.0.0               crosstalk_1.0.0         yaml_2.2.0              blogdown_0.11           xfun_0.11               fastmap_1.0.1           e1071_1.7-3             knitr_1.23              raster_3.0-7           
[28] leaflet.providers_1.9.0 htmlwidgets_1.5.1       webshot_0.5.2           classInt_0.4-2          stats4_3.5.1            leaflet_2.0.3           grid_3.5.1              sf_0.8-0                R6_2.4.1               
[37] processx_3.4.1          rmarkdown_1.12          bookdown_0.9            leafpop_0.0.1           sp_1.3-2                callr_3.3.2             magrittr_1.5            ps_1.3.0                units_0.6-5            
[46] scales_1.1.0            promises_1.1.0          codetools_0.2-15        htmltools_0.4.0         mime_0.7                xtable_1.8-4            colorspace_1.4-1        httpuv_1.5.2            KernSmooth_2.23-15     
[55] munsell_0.5.0           leafem_0.0.1      
```

**Comment by tim-salabim** [comment] 2019-11-27 02:57
Did this happen after you upgraded to leaflet_2.0.3?

**Comment by SimonCoulombe** [comment] 2019-11-30 19:09
Thanks for replying!

This is the first time I try mapshot(), so I don't have any point of reference.

**Comment by tim-salabim** [comment] 2019-12-14 12:05
Sorry, but I cannot reproduce this. Works fine for me...

**Comment by SimonCoulombe** [comment] 2019-12-14 18:04
No worries  - big thanks for having a look!
I tried rebooting just in case, didnt solve it.

**Comment by tim-salabim** [comment] 2019-12-19 17:55
The only other reason for this behaviour that I can think of is a slow internet connection. You could try adding `delay = 5` to your mapshot call to see whether that produces anything.

**Comment by tim-salabim** [comment] 2019-12-19 18:14
On second thought, you could also set `remove_url = FALSE` and see whether the temporary interactive map renders fine.

**Comment by SimonCoulombe** [comment] 2020-04-11 03:12
It's been 4 months and a few upgrades from ubuntu 18.10 to 19.10, but I have the same error.  when I add a delay and a remove_url.  The problem isnt with mapshot  because webshot::webshot("www.google.com") returns the same error..


mapshot(m, file = paste0(getwd(), "/map.png"), remove_url = FALSE, delay = 5)

TypeError: Attempting to change the setter of an unconfigurable property.
TypeError: Attempting to change the setter of an unconfigurable property



> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes   


> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.7.8

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6            RColorBrewer_1.1-2      compiler_3.6.1          base64enc_0.1-3         class_7.3-15            tools_3.6.1             uuid_0.1-4             
 [8] digest_0.6.25           packrat_0.5.0           jsonlite_1.6.1          satellite_1.0.2         evaluate_0.14           lifecycle_0.2.0         lattice_0.20-38        
[15] viridisLite_0.3.0       png_0.1-7               rlang_0.4.5             DBI_1.1.0               crosstalk_1.1.0.1       yaml_2.2.1              blogdown_0.18          
[22] xfun_0.12               e1071_1.7-3             raster_3.0-12           knitr_1.28              leaflet.providers_1.9.0 systemfonts_0.1.1       gdtools_0.2.2          
[29] htmlwidgets_1.5.1       stats4_3.6.1            classInt_0.4-3          leaflet_2.0.3           grid_3.6.1              webshot_0.5.2           svglite_1.2.3          
[36] sf_0.9-1                R6_2.4.1                processx_3.4.2          rmarkdown_2.1           bookdown_0.18           leafpop_0.0.5           sp_1.4-1               
[43] callr_3.4.3             magrittr_1.5            ps_1.3.2                scales_1.1.0            codetools_0.2-16        htmltools_0.4.0         units_0.6-6            
[50] colorspace_1.4-1        brew_1.0-6              KernSmooth_2.23-15      munsell_0.5.0           leafem_0.1.1

**Comment by tim-salabim** [comment] 2020-04-11 08:20
Nice! Note, I've just pushed an update to mapshot yesterday. Now there is no `remove_url` anymore, we simply assume that if no url is provided we don't want to keep it...

Closing here

**Closed by tim-salabim** 2020-04-11 08:20 UTC
