### ISSUE TITLE
SpatVector and SpatRaster inputs

### ISSUE THREAD

**Issue by AMBarbosa** [r-spatial/mapview#432] opened 2022-06-22 17:11 UTC
Thanks for this amazing package! I realize that `mapView()` already implements a lot of data inputs, but is there any chance it could also implement the (also widely and increasingly used) SpatVector and SpatRaster formats? Cheers!

**Comment by GreatEmerald** [comment] 2022-06-28 16:34
This is a duplicate of #340. Though it's getting more urgent (I'm getting crazy CRS handling in the old raster package on the latest rolling release distro, it's probably only going to get worse from here on out).

**Comment by tim-salabim** [comment] 2022-06-29 08:24
> though I'm very wary of touching other people's code, especially in complex packages where I could break something elsewhere ;)
I hear ya, will implement this soon (hopefully)

**Comment by AMBarbosa** [comment] 2022-06-29 11:38
I've just tried it on my end and indeed that fails, but not if you separate the commands:
```
strs <- st_as_stars(rast(system.file("ex/meuse.tif", package="terra")))
mapview(strs)
```
It looks like it has to do with `validateScalarName()` being applied to the entire file path, which contains "/".

**Comment by tim-salabim** [comment] 2022-06-29 11:58
This is JavaScript biting us here:

```r
htmltools:::validateScalarName
function (x, name = deparse(substitute(x))) 
{
    if (length(x) != 1 || x == "" || grepl("[/\\]", x)) 
        stop("Invalid argument '", name, "' (must be a non-empty character string and contain no '/' or '\\')")
}
<bytecode: 0x564dea5d9140>
<environment: namespace:htmltools>
```
and yes, `mapview` is trying to infer the layer name using `deparse(subsitute(x))` so those slashes are carried forward to leaflet -> htmltools... I'll have a look how to avoid those

**Comment by GreatEmerald** [comment] 2022-06-29 12:01
Good to know that was a JavaScript issue; indeed when separated the command works, but then if I try to `plot(r)`, my R session explodes with `Error: C stack usage  46814669739132 is too close to the limit`, hence why I thought it could be an issue in `stars`. But perhaps it's something with my software stack...

**Comment by tim-salabim** [comment] 2022-06-29 12:02
@edzer I agree, using `names()` is a better approach for raster data. This is what we do in the `raster` method. Not sure why this is not done in the `stars` method. I'll investigate.

**Comment by AMBarbosa** [comment] 2022-07-11 10:18
In case it help, the latest version of `leaflet` now accepts SpatRaster (https://github.com/rstudio/leaflet/blob/main/man/addRasterImage.Rd) and SpatVector inputs (e.g. https://github.com/rstudio/leaflet/blob/main/man/leaflet.Rd).

**Comment by Nowosad** [comment] 2022-12-05 14:52
@tim-salabim Close?

**Comment by tim-salabim** [comment] 2023-01-06 11:00
yip, closing

**Closed by tim-salabim** 2023-01-06 11:00 UTC
