### ISSUE TITLE
Is it possible to include mapview in RPresentation?

### ISSUE THREAD

**Issue by ibarraespinosa** [r-spatial/mapview#103] opened 2017-10-10 04:39 UTC
I would like to include mapview in Rpresentation but I have an error of no connection 'rb'

Is it possible?

Thanks

**Comment by tim-salabim** [comment] 2017-10-10 05:48
can you provide a reproducible example?

**Comment by ibarraespinosa** [comment] 2017-10-10 15:51
I'm adding example in few hours

**Comment by ibarraespinosa** [comment] 2017-10-11 03:27
teste
========================================================
author: 
date: 
autosize: true

First Slide
========================================================
```{r}
library(mapview)
mapview(breweries)
```

------------------------------------------------------------------------------------------

Resulted in:

------------------------------------------------------------------------------------------
First Slide

Error in file(con, "rb") : it is not possible to open the connection

------------------------------------------------------------------------------------------

Here a screenshot: https://imgur.com/a/U3HeI

**Comment by tim-salabim** [comment] 2017-10-11 05:45
works for me...

![screenshot at 2017-10-11 07 44 52](https://user-images.githubusercontent.com/2826432/31423991-1faab270-ae58-11e7-94fb-72953e433e4e.png)

**Comment by ibarraespinosa** [comment] 2017-10-11 12:45
Here my session info:

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.04

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pt_BR.UTF-8        LC_COLLATE=pt_BR.UTF-8    
 [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=pt_BR.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.0.1 leaflet_1.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12      raster_2.5-8      magrittr_1.5      units_0.4-5      
 [5] gdalUtils_2.0.1.7 munsell_0.4.3     viridisLite_0.2.0 colorspace_1.3-2 
 [9] xtable_1.8-2      lattice_0.20-35   R6_2.2.2          foreach_1.4.3    
[13] udunits2_0.13     plyr_1.8.4        tools_3.4.1       webshot_0.4.1    
[17] rgdal_1.2-8       grid_3.4.1        png_0.1-7         R.oo_1.21.0      
[21] DBI_0.7           htmltools_0.3.6   crosstalk_1.0.0   iterators_1.0.8  
[25] yaml_2.1.14       digest_0.6.12     sf_0.5-3          shiny_1.0.3      
[29] base64enc_0.1-3   htmlwidgets_0.8   R.utils_2.5.0     codetools_0.2-15 
[33] mime_0.5          sp_1.2-5          compiler_3.4.1    scales_0.4.1     
[37] R.methodsS3_1.7.1 stats4_3.4.1      jsonlite_1.5      satellite_0.2.0  
[41] httpuv_1.3.3   

```

**Comment by tim-salabim** [comment] 2017-10-12 06:15
Try updating to the current development version from github.
```r
devtools::install_github("r-spatial/mapview@develop")
```

**Comment by ibarraespinosa** [comment] 2017-10-15 17:56
i installed the updated version of mapview but i could not see the map. http://www.rpubs.com/djxhie/rpresmap . I believe that it is a problem with Rpres. mapview works fine with rmarkdown templates.

**Comment by tim-salabim** [comment] 2017-11-02 20:09
Can we close this?

**Comment by ibarraespinosa** [comment] 2017-11-02 21:09
@tim-salabim yes. However, although I upgraded Ubuntu, R and repeated the steps and I could not use it in Rpres. At the end, I used mapview in another presentation. Thanks

**Comment by tim-salabim** [comment] 2017-11-02 21:12
Cool. Thanks!

**Closed by tim-salabim** 2017-11-02 21:12 UTC
