### ISSUE TITLE
Legend colors do not match map colors

### ISSUE THREAD

**Issue by emochoa** [r-spatial/mapview#219] opened 2019-04-02 03:02 UTC
Greetings.

There are several situations in which the mapview legend shows colors that do not match those used in the map.  Here is an example of one such situation, using a discrete legend:

```
library(leaflet)
library(mapview)

pink <- colorBin(c('white', 'deeppink'), domain = NULL)
mapview(franconia, alpha.regions = 1, map.types = 'CartoDB.Positron',
        layer.name = 'Franconia', zcol = 'SHAPE_AREA',
        col.regions = pink(franconia$SHAPE_AREA), at = seq(0, .25, .035))
```

![image](https://user-images.githubusercontent.com/22716026/55372963-34a68a00-54c9-11e9-8202-68fd81932e6b.png)

Ordinarily, I would make the legend in leaflet, but I am hoping to have two separate choropleth layers, each with their own legend, in a single mapview widget.  If it's possible to do this, with legends that match the color palette, that would be great.

Thank you for your time and consideration.

**Comment by ggeniaux** [comment] 2019-05-21 07:18
Same type of issues, when using "at" with quantile, legend colors don't match maps colors.

```
pal = mapviewPalette("mapviewRasterColors")

mapview(mygrid['prix_liss'],at = quantile(mygrid$prix_liss,prob=seq(0,1,by=0.05)),col.regions = pal(20))
```

![Capture d’écran 2019-05-21 à 09 15 19](https://user-images.githubusercontent.com/6615871/58075868-1136bc00-7ba9-11e9-8f84-adf0abeed1ed.png)


Any suggestions to avoid this issue are welcome.

**Comment by tim-salabim** [comment] 2019-05-29 18:04
Sorry for the long silence. When we don't use `colorBin` but `colorRampPalette` then things should be fine.

```r
library(leaflet)
library(mapview)

pink2 = colorRampPalette(c('white', 'deeppink'))

mapview(franconia, alpha.regions = 1, map.types = 'CartoDB.Positron',
        layer.name = 'Franconia', zcol = 'SHAPE_AREA',
        col.regions = pink2, at = seq(0, .25, .035))
```
gives

![Screenshot from 2019-05-29 20-02-38](https://user-images.githubusercontent.com/2826432/58580179-cbcf5a00-824c-11e9-8467-12285266d5f2.png)

@ggeniaux can you please try this also with your example (which I cannot reproduce)?

**Comment by tim-salabim** [comment] 2019-05-29 18:06
actually, @ggeniaux your example will work propably just fine when you use `col.regions = pal` instead of `col.regions = pal(20)`

**Comment by ggeniaux** [comment] 2019-05-29 18:08
Thanks a lot, Tim. I will test both as soon as possible.
Ghislain.


actually, @ggeniaux<https://github.com/ggeniaux> your example will work propably just fine when you use col.regions = pal instead of col.regions = pal(20)


Le 29 mai 2019 à 20:04, tim-salabim <notifications@github.com<mailto:notifications@github.com>> a écrit :


Sorry for the long silence. When we don't use colorBin but colorRampPalette then things should be fine.

library(leaflet)
library(mapview)

pink2 = colorRampPalette(c('white', 'deeppink'))

mapview(franconia, alpha.regions = 1, map.types = 'CartoDB.Positron',
        layer.name = 'Franconia', zcol = 'SHAPE_AREA',
        col.regions = pink2, at = seq(0, .25, .035))

gives

[Screenshot from 2019-05-29 20-02-38]<https://user-images.githubusercontent.com/2826432/58580179-cbcf5a00-824c-11e9-8467-12285266d5f2.png>

@ggeniaux<https://github.com/ggeniaux> can you please try this also with your example (which I cannot reproduce)?

**Comment by emochoa** [comment] 2019-06-01 20:36
@tim-salabim, thank you so much.  I will use this in future maps.

One thing I noticed with `colorRampPalette` is that unlike a palette created with `colorBin`, it can't be passed to a leaflet legend.  If I recall correctly, the only reason I've needed for this is to reverse a legend, but we can do that by calling `rev` on the argument being passed to the `at` parameter:

```
library(leaflet)
library(mapview)

pink2 = colorRampPalette(c('white', 'deeppink'))
mapview(franconia, alpha.regions = 1, map.types = 'CartoDB.Positron',
        layer.name = 'Franconia', zcol = 'SHAPE_AREA', legend = TRUE,
        col.regions = pink2, at = rev(seq(0, .25, .035)))
```
![image](https://user-images.githubusercontent.com/22716026/58753325-e4c15080-8482-11e9-8168-6a2f442ad64f.png)

**Comment by tim-salabim** [comment] 2019-06-03 06:56
Closing here, feel free to reopen if anything unexpected comes up

**Closed by tim-salabim** 2019-06-03 06:56 UTC

**Comment by meteosimon** [comment] 2019-06-07 15:23
Hi there,
I was trying to mapview a sf object, just like this (found [here](https://r-spatial.github.io/sf/articles/sf5.html)):

    library(sf)
    library(mapview)
    demo(nc, ask = FALSE, echo = FALSE)
    plot(nc["BIR74"])
    mapview(nc["BIR74"], col.regions = sf.colors(10))
    mapview(nc["BIR74"], col.regions = sf.colors(100))
    mapview(nc["BIR74"], col.regions = sf.colors(101))
    mapview(nc["BIR74"], col.regions = sf.colors)

and was running into the same issue. Using the palette function rather than a vector with colors easily solves the problem. However, it does not prevent other user to run into the same problem.

I think mapview should at least warn the user when a vector of colors is used, or better fix the length of the vector to avoid this stange behaviour.
Cheers,
Thorsten
